# frozen_string_literal: true

handle = File.open('evtcs/20180514-224431.evtc', 'rb')

header = handle.read(16)

version, area = header.unpack('Z12xh4x')
number_of_agents = handle.read(4).unpack1('L')

agents = []

Agent = Struct.new(:addr, :prof, :elite, :toughness, :concentration, :healing, :hitbox_width, :condition, :hitbox_height, :name, :player, :group)

toughness = concentration = healing = condition = 1

number_of_agents.times do
  agent = handle.read(96).unpack('QLLS6Z*Z*Z')
  agents << Agent.new(*agent)
  next unless agents.last.elite != 0xffffffff

  toughness = [toughness, agents.last.toughness].max
  concentration = [concentration, agents.last.concentration].max
  healing = [healing, agents.last.healing].max
  condition = [condition, agents.last.condition].max
end

number_of_skills = handle.read(4).unpack1('L')

agents = agents.reject { |a| a.player == '' }

puts <<~INFO
  This log is for area #{area} and was generated by ArcDPS #{version[-8..-1]}

  Arc detected #{number_of_agents} agents.
  Arc detected #{number_of_skills} skills.

  Max Healing: #{healing}, Max Condition: #{condition}, Max Toughness: #{toughness}, Max Concentration: #{concentration}

  Here are the unique agents by name:
  #{agents.map(&:inspect).join("\n")}
INFO
