handle = File.open('evtcs/20180514-224431.evtc', 'rb')

header = handle.read(16)

version, area = header.unpack('Z12xh4x')
number_of_agents = handle.read(4).unpack('L').first

agents = []

Agent = Struct.new(:addr, :prof, :elite?, :toughness, :concentration, :healing, :pad1, :condition, :pad2, :char, :player, :group)

number_of_agents.times do
  agent = handle.read(96).unpack('QLLssssssZ*Z*Z')
  agents << Agent.new(*agent)
end

agents = agents.select {|a| a.player != "" }

puts <<~INFO
  This log is for area #{area} and was generated by ArcDPS #{version[-8..-1]}

  Arc detected #{number_of_agents} agents.

  Here are the unique agents by name:
  #{agents.map(&:inspect).join("\n")}
INFO
